export const SSR: Array<any> = [
  {
    id: 111,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Amezaiku",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644669133/rstriyywjxcyqfp5tiz7.jpg",
  },
  {
    id: 80,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Aobozu",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667916/sdurzbrasczgxfwzcufa.jpg",
  },
  {
    id: 57,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Azurestorm Ichimokuren",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667445/manluk5liysyyuoe7yy2.jpg",
  },
  {
    id: 102,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Bake Kujira",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668883/hq5j7nlmzn4jexuulr6a.jpg",
  },
  {
    id: 58,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Blazing Tamamonomae",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667467/lc7ioglgykqvupb9x8i1.jpg",
  },
  {
    id: 91,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Bukkuman",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668106/pjfwfts6eameu5zuqzfo.jpg",
  },
  {
    id: 87,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Chin",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668023/r2ygncihavver3so5s3s.jpg",
  },
  {
    id: 34,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Crimson Yoto",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644656900/ryfk6nufn9o0t9xvnrpf.jpg",
  },
  {
    id: 59,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Demoniac Shuten Doji",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667491/x0ngr2nei46d5in0dfxv.jpg",
  },
  {
    id: 32,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Divine Miketsu",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644656758/j05p46xkscauubs01mdp.jpg",
  },
  {
    id: 92,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Doumeki",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668118/a93cqr9yopqg0zwjroqa.jpg",
  },
  {
    id: 77,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Ebisu",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667867/n6mwwziyokgubuczooin.jpg",
  },
  {
    id: 85,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Enenra",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667998/glyaqhabsmge3fxodmde.jpg",
  },
  {
    id: 45,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Frosty Yuki Onna",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657212/q1sccbc6cuxysxm3hkrf.jpg",
  },
  {
    id: 108,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Furi",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644669071/dspushm0r3dfvcezpj6r.jpg",
  },
  {
    id: 74,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Futakuchi",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667831/ovfdlpmdgm5ky5e8tpd9.jpg",
  },
  {
    id: 41,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Guardian Ubume",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657116/g3heyh36fnkpm9m9ajz2.jpg",
  },
  {
    id: 89,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hako Shoujo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668062/tqneoxvcsc34qb0zhsue.jpg",
  },
  {
    id: 75,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hakuro",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667844/npvixvdcgs8hmnvbvssr.jpg",
  },
  {
    id: 65,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hangan",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667675/zitc1gxmeewsn7dbujq0.jpg",
  },
  {
    id: 79,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hannya",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667901/isgck9dm07123luojz8a.jpg",
  },
  {
    id: 94,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hiyoribo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668155/ejkdxbwvueiba8sdyomy.jpg",
  },
  {
    id: 55,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hone Onna",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667272/lrlng9yu8zue5ciyliul.jpg",
  },
  {
    id: 107,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hoshiguma Doji",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644669057/gbntqnpmkegzf6nipuvt.jpg",
  },
  {
    id: 66,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Hounouka",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667693/sqlwx58qwklan8o8p3sa.jpg",
  },
  {
    id: 48,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Inaba Kaguya",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657327/rbzyshhffah01nuw5u9o.jpg",
  },
  {
    id: 31,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Inferno Ibaraki Doji",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644656348/av0ytx1lfvmva6ko8p0c.jpg",
  },
  {
    id: 54,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Inugami",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667249/kdwhjugqknzli4rajqnw.jpg",
  },
  {
    id: 88,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Itsumade",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668039/veqwl0tqpadix5whqhhp.jpg",
  },
  {
    id: 100,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Ittan Momen",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668853/htdpbtoo2wt9w0ay5k5e.jpg",
  },
  {
    id: 98,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Jinmenju",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668240/nbsnyxpnjopodflezkqe.jpg",
  },
  {
    id: 78,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Jorogumo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667884/myusvzzulnc29wspb42z.jpg",
  },
  {
    id: 60,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Jr. Ootengu",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667529/j8ydzfqekustcbmvpn9k.jpg",
  },
  {
    id: 103,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kainin",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668896/wjxva3x1ufptzmxcqkuw.jpg",
  },
  {
    id: 72,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kamaitachi",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667796/wixzxsj7sooezqrfqpat.jpg",
  },
  {
    id: 106,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kamimai",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668977/uv6fhktdvoqpnxrbx8t3.jpg",
  },
  {
    id: 105,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kanihime",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668961/ohmtcf9jxmd6hsywjo0v.jpg",
  },
  {
    id: 95,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kaoru",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668178/yschr89yramv5rdmys9i.jpg",
  },
  {
    id: 112,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kawazaru",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644669151/jsgz3kxlovwit1jywlu8.jpg",
  },
  {
    id: 86,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kingyo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668011/gapapcnzjka3xlleagcj.png",
  },
  {
    id: 96,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kisei",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668201/m8o0dkmqx7hue1wldqf8.jpg",
  },
  {
    id: 71,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kiyohime",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667775/weff9qbaxcdcxnm7lipl.jpg",
  },
  {
    id: 90,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Komatsu",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668090/nlutzorjr7p9aqwux67a.jpg",
  },
  {
    id: 104,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kujira",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668919/yjdqmpsid8sa7lsg0mgw.jpg",
  },
  {
    id: 83,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kuro",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667957/z2f5cnpe1o9jcp6hcrpk.jpg",
  },
  {
    id: 52,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kuro Mujo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667200/y2vrbpj4vpavnbblvnra.jpg",
  },
  {
    id: 62,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Kyonshi Ani",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667624/hz19wlz8vhtr2dzqcqpd.jpg",
  },
  {
    id: 40,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Lovebound Kiyohime",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657093/tjlboqdwirjau5t2lrxy.jpg",
  },
  {
    id: 69,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Maestro",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667743/xkcfug2o3v9veprpwroi.jpg",
  },
  {
    id: 81,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Mannendake",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667930/tln8pw9eg4b0mq1wzmhv.png",
  },
  {
    id: 56,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Momiji",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667284/uwkkqdeuoeizrfr2cjwd.jpg",
  },
  {
    id: 49,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Momo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644666443/bl9clfktcpwaklx90y1b.jpg",
  },
  {
    id: 42,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Monumental Otakemaru",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657141/j3hqnc3hufqzayhmmngh.jpg",
  },
  {
    id: 53,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Mouba",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667232/v6sxqizkiamjdcdwkmy8.jpg",
  },
  {
    id: 97,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Nekomata",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668224/kauhefxv5at1rp2zjtqx.jpg",
  },
  {
    id: 44,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Nightveil Higabana",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657187/dffzsbaazfxl2d2ypxud.jpg",
  },
  {
    id: 110,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Nyunai Suzume",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644669115/iwhay4knhhyhuwqxaenl.jpg",
  },
  {
    id: 93,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Oitsuki",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668134/fat8ogqqhgotpb7ukvxa.jpg",
  },
  {
    id: 99,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Okikumushi",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668260/edaqizem0c4gtu44ea9b.jpg",
  },
  {
    id: 101,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Okurubito",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644668869/wgbr1keui1mvd00mtgsy.jpg",
  },
  {
    id: 37,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Onikiri Reforged",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657007/r5y7wjfsgfbvrsvgexq3.jpg",
  },
  {
    id: 63,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Puppeteer",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667640/ppxvnuyn5dkqw4pleyfw.jpg",
  },
  {
    id: 76,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Sakura",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667856/fy3enp6tocpjwuwodbdd.jpg",
  },
  {
    id: 109,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Sasori",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644669088/yis0jzijawg3xto9rn1a.jpg",
  },
  {
    id: 38,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Seawatch Kingyo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657032/p6dmpxhjr41xhblcghzw.jpg",
  },
  {
    id: 84,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Shiro",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667968/oa9v9ameu0seqnzolyal.jpg",
  },
  {
    id: 51,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Shiro Mujo",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667145/lrhou99mdwyo9c714xu8.jpg",
  },
  {
    id: 73,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Ubume",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667815/mdsw4eqjdkk6omdoc8jt.jpg",
  },
  {
    id: 64,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Umibozu",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667655/cqtgapfdgs2bz08hm3y6.jpg",
  },
  {
    id: 43,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Valiant Yamakaze",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657158/nm3gziywscszogqswuv2.jpg",
  },
  {
    id: 67,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Vampira",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667712/a82zxplb3dfe0oiebbd6.jpg",
  },
  {
    id: 61,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Vengeful Hannya",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667576/fh3ay5dlczyoutuiszid.jpg",
  },
  {
    id: 47,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Virtuoso Hanna",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657297/ppoxhum8ua7y6evbguyv.jpg",
  },
  {
    id: 46,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Void Menreiki",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657237/h8ovcs3hnslcs2kdsuc4.jpg",
  },
  {
    id: 35,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Waverider Lord Arakawa",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644656934/uc0hxaxb7gkpuhemxj3r.jpg",
  },
  {
    id: 39,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Worldly Aoandon",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644657063/xuzfu0vj3p2t3oahlxtk.jpg",
  },
  {
    id: 82,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Yasha",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667945/jjvi83ftmxxcpcd6mvta.jpg",
  },
  {
    id: 68,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Youko",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667725/gryppjfghelpdbsnr1do.jpg",
  },
  {
    id: 50,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Yuki Onna",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644666470/sxhhwd4rvpcsomsyq3ht.jpg",
  },
  {
    id: 70,
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    name: "Yumekui",
    img: "http://res.cloudinary.com/onmyojiimage/image/upload/v1644667758/vrhbskotzezjqvq5sbsv.jpg",
  },
];
