export const SSR: Array<any> = [
  {
    id: 0,
    name: "Nhất Mục Liên",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 1,
    name: "Thanh Hành Đăng ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 2,
    name: "Yêu Đao Cơ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 3,
    name: "Diêm Ma",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 4,
    name: "Hoang Xuyên chi Chủ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 5,
    name: "Đại Thiên Cẩu ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 6,
    name: "Tửu Thôn Đồng Tử ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 7,
    name: "Tỳ Mộc Đồng Tử ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 8,
    name: "Tiểu Lộc Nam ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 9,
    name: "Hoang ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 10,
    name: "Hoa Điểu Quyển ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 11,
    name: "Huy Dạ Cơ ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 12,
    name: "Tuyết Đồng Tử ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 13,
    name: "Bỉ Ngạn Hoa ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 14,
    name: "Ngự Soạn Tân ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 15,
    name: "Ngọc Tảo Tiền ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 16,
    name: "Diện Linh Khí ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 17,
    name: "Bát Kỵ Đại Xà ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 18,
    name: "Đại Nhạc Hoàn ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 19,
    name: "Bất Tri Hỏa ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 20,
    name: "Quỷ Thiết ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 21,
    name: "Ngự Oán Bát Nhã ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 22,
    name: "Thương Phong Nhất Mục Liên ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 23,
    name: "Luyện Ngục Tỳ Mộc Đồng Tử ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 24,
    name: "Thiếu Vũ Đại Thiên Cẩu ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 25,
    name: "Xích Ảnh Yêu Đao Cơ ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
  {
    id: 26,
    name: "Đạo Hà Thần Ngự Soạn Tân ",
    disable: false,
    bluePick: false,
    pickAction: false,
    redPick: false,
    img: "341skin1.png",
  },
];
